# Generated by Django 5.0.6 on 2024-06-15 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_rename_the_user_listing_seller_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing',
            new_name='the_listing',
        ),
    ]
